# version: "3.9"

services:

  gateway:
    build:
      context: ./services/gateway
    ports:
      - "3000:3000"
    env_file:
      - ./services/gateway/.env
    environment:
      - AUTH_SERVICE_URL=http://auth:3001
      - BOOK_SERVICE_URL=http://book:3002
      - ORDER_SERVICE_URL=http://order:3003
    # depends_on:
    #   - postgres

  auth:
    build:
      context: ./services/auth
    ports:
      - "3001:3001"
    env_file:
      - ./services/auth/.env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: bookverse
      DB_PASSWORD: bookverse
      DB_NAME: bookverse_auth
    depends_on:
      - postgres

  book:
    build:
      context: ./services/book
    ports:
      - "3002:3002"
    # env_file:
    #   - ./services/book/.env
    environment:
      - MONGO_URL=mongodb://mongodb:27017/bookverse_books
    depends_on:
      - mongodb

  order:
    build:
      context: ./services/order
    ports:
      - "3003:3003"
    # env_file:
    #   - ./services/order/.env
    environment:
      - MONGO_URL=mongodb://mongodb:27017/bookverse_books
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq

  notification:
    build:
      context: ./services/notification
    # ports:
    #   - "3001:3001"
    # env_file:
    #   - ./services/notification/.env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
      - mongodb

  user:
    build:
      context: ./services/user
    ports:
      - "3004:3004"
    env_file:
      - ./services/user/.env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: bookverse
      DB_PASSWORD: bookverse
      DB_NAME: bookverse_auth
    depends_on:
      - postgres

  review:
    build:
      context: ./services/review
    ports:
      - "3005:3005"
    env_file:
      - ./services/review/.env
    environment:
      - MONGO_URL=mongodb://mongodb:27017/bookverse_books
      # DB_HOST: postgres
      # DB_PORT: 5432
      # DB_USERNAME: bookverse
      # DB_PASSWORD: bookverse
      # DB_NAME: bookverse_auth
    depends_on:
      - mongodb

  postgres:
    image: postgres:16
    container_name: bookverse-postgres
    environment:
      POSTGRES_USER: bookverse
      POSTGRES_PASSWORD: bookverse
      POSTGRES_DB: bookverse_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_primary:
    image: postgres:16-alpine
    container_name: postgres_primary
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bookverse
      POSTGRES_PASSWORD: bookverse
      POSTGRES_DB: bookverse_auth
      # Configures access rules to allow replication protocols from any IP internally
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256

        host replication replicator 0.0.0.0/0 md5"
    command: |
      postgres
      -c wal_level=replica
      -c max_wal_senders=5
      -c max_replication_slots=5
      -c hot_standby=on
    # Configures synchronous replication to ensure that transactions are committed on both primary and replica before returning success
    # -c synchronous_commit=on
    # -c synchronous_standby_names='*'

    volumes:
      - ./init-primary.sql:/docker-entrypoint-initdb.d/init-primary.sql
      - primary_data:/var/lib/postgresql/data

  postgres_replica:
    image: postgres:16-alpine
    container_name: postgres_replica
    restart: always
    ports:
      - "5433:5432"
    user: postgres
    environment:
      PGUSER: replicator
      PGPASSWORD: replicator_password
      # By pointing PGDATA to a subfolder, we avoid permission bugs on the root volume mount
      PGDATA: /var/lib/postgresql/data/replica_db
    depends_on:
      - postgres_primary
    # The command waits for primary, clears the local data folder, streams a backup, then starts up
    command: |
      bash -c "
      until pg_isready -h postgres_primary -p 5432; do
        echo 'Waiting for primary...'
        sleep 2
      done
      # Clean out the subdirectory completely
      rm -rf /var/lib/postgresql/data/replica_db

      # Stream the backup directly into the subdirectory
      pg_basebackup -h postgres_primary -D /var/lib/postgresql/data/replica_db -U replicator -vP -R --slot=main_replica_slot

      exec postgres
      "
    volumes:
      - replica_data:/var/lib/postgresql/data


  postgres_replica_2:
    image: postgres:16-alpine
    container_name: postgres_replica_2
    restart: always
    ports:
      - "5434:5432"
    user: postgres
    environment:
      PGUSER: replicator
      PGPASSWORD: replicator_password
      # By pointing PGDATA to a subfolder, we avoid permission bugs on the root volume mount
      PGDATA: /var/lib/postgresql/data/replica_db
    depends_on:
      - postgres_primary
    # The command waits for primary, clears the local data folder, streams a backup, then starts up
    command: |
      bash -c "
      until pg_isready -h postgres_primary -p 5432; do
        echo 'Waiting for primary...'
        sleep 2
      done
      # Clean out the subdirectory completely
      rm -rf /var/lib/postgresql/data/replica_db

      # Stream the backup directly into the subdirectory
      pg_basebackup -h postgres_primary -D /var/lib/postgresql/data/replica_db -U replicator -vP -R --slot=main_replica_slot

      exec postgres
      "
    volumes:
      - replica_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-visualizer
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: YourSecurePassword
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  mongodb:
    image: mongo:7
    container_name: bookverse-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: bookverse-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bookverse-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
  mongo_data:
  primary_data:
  replica_data:

    # docker compose up --build --force-recreate --no-cache && docker image prune -f
    # docker compose build --no-cache && docker compose up --force-recreate
