# version: "3.9"

services:

  gateway:
    build:
      context: ./services/gateway
    ports:
      - "3000:3000"
    env_file:
      - ./services/gateway/.env
    environment:
      - AUTH_SERVICE_URL=http://auth:3001
      - BOOK_SERVICE_URL=http://book:3002
      - ORDER_SERVICE_URL=http://order:3003

    # depends_on:
    #   - postgres

  auth:
    build:
      context: ./services/auth
    ports:
      - "3001:3001"
    env_file:
      - ./services/auth/.env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: bookverse
      DB_PASSWORD: bookverse
      DB_NAME: bookverse_auth
    depends_on:
      - postgres

  book:
    build:
      context: ./services/book
    ports:
      - "3002:3002"
    # env_file:
    #   - ./services/book/.env
    environment:
      - MONGO_URL=mongodb://mongodb:27017/bookverse_books
    depends_on:
      - mongodb
  
  order:
    build:
      context: ./services/order
    ports:
      - "3003:3003"
    # env_file:
    #   - ./services/order/.env
    environment:
      - MONGO_URL=mongodb://mongodb:27017/bookverse_books
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq

  notification:
    build:
      context: ./services/notification
    # ports:
    #   - "3001:3001"
    # env_file:
    #   - ./services/notification/.env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
      - mongodb

  user:
    build:
      context: ./services/user
    ports:
      - "3004:3004"
    env_file:
      - ./services/user/.env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: bookverse
      DB_PASSWORD: bookverse
      DB_NAME: bookverse_auth
    depends_on:
      - postgres

  review:
    build:
      context: ./services/review
    ports:
      - "3005:3005"
    env_file:
      - ./services/review/.env
    environment:
      - MONGO_URL=mongodb://mongodb:27017/bookverse_books
      # DB_HOST: postgres
      # DB_PORT: 5432
      # DB_USERNAME: bookverse
      # DB_PASSWORD: bookverse
      # DB_NAME: bookverse_auth
    depends_on:
      - mongodb


  postgres:
    image: postgres:16
    container_name: bookverse-postgres
    environment:
      POSTGRES_USER: bookverse
      POSTGRES_PASSWORD: bookverse
      POSTGRES_DB: bookverse_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-visualizer
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: YourSecurePassword
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  mongodb:
    image: mongo:7
    container_name: bookverse-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: bookverse-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bookverse-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
  mongo_data:








# docker compose up --build --force-recreate --no-cache && docker image prune -f
# docker compose build --no-cache && docker compose up --force-recreate
