import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';
import { trace } from '@opentelemetry/api';

@Injectable()
export class EnterpriseLoggerMiddleware implements NestMiddleware {
  use(req: Request, res: Response, next: NextFunction) {
    const startTime = Date.now();

    // Listen to when the request finishes to calculate latency and bytes sent
    res.on('finish', () => {
      const durationMs = Date.now() - startTime;
      
      // Extract the active traceId generated by OpenTelemetry
      const activeSpan = trace.getActiveSpan();
      const traceId = activeSpan ? activeSpan.spanContext().traceId : req.headers['x-request-id'] || 'no-trace-id';

      const logPayload = {
        timestamp: new Date().toISOString(),
        service_name: process.env.OTEL_SERVICE_NAME || 'nestjs-service',
        trace_id: traceId,
        request_id: req.headers['x-request-id'] || null, // Tied back to Nginx $request_id if passed
        client_ip: req.ip || req.headers['x-forwarded-for'] || null,
        method: req.method,
        uri: req.originalUrl,
        status: res.statusCode,
        bytes_sent: parseInt(res.get('Content-Length') || '0', 10),
        latency_ms: durationMs,
        http_referrer: req.get('referrer') || null,
        user_agent: req.get('user-agent') || null,
      };

      // Print it out as a single-line JSON string for Loki/Grafana to parse effortlessly
      console.log(JSON.stringify(logPayload));
    });

    next();
  }
}