GET http://localhost:3007/health/live HTTP/1.1

###
GET http://localhost:3007/health/ready HTTP/1.1

###
POST http://localhost:3007/reviews HTTP/1.1
content-type: application/json

{
  "bookId": "bk_987654321",
  "userId": "usr_01HJ7Y62X",
  "rating": 5,
  "comment": "An absolute masterpiece. The world-building is deeply layered and the pacing is perfect!",
  "isVerifiedUser": true,
  "isPremiumUser": false,
  "productId" : "4ca3b6e3-7821-4f1b-a19c-0728c03fa042"
}

###
GET http://localhost:3007/reviews/735e7324-a003-4571-a113-90ec71d31b9a HTTP/1.1


###
GET http://localhost:3007/reviews/product/4ca3b6e3-7821-4f1b-a19c-0728c03fa042 HTTP/1.1

###
PATCH http://localhost:3007/reviews/2a0308a8-2b99-45b5-9134-2dd648523d31 HTTP/1.1
content-type: application/json

{
  "bookId": "bk_987654321",
  "userId": "usr_01HJ7Y62X",
  "rating": 4,
  "comment": "An absolute masterpiece. The world-building is deeply layered and the pacing is perfect!",
  "isVerifiedUser": true,
  "isPremiumUser": false,
  "productId" : "4ca3b6e3-7821-4f1b-a19c-0728c03fa042",
  "reportCount": 1,
  "isAuthorBlocked": false,
  "isSoftDeleted": true,
  "isHidden": false
}



###
DELETE http://localhost:3007/reviews/735e7324-a003-4571-a113-90ec71d31b9a HTTP/1.1
