apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.book.replicaCount }}
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book
          image: "{{ .Values.book.image.repository }}:{{ .Values.book.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.book.service.port }}

          envFrom:
            - configMapRef:
                name: app-config

            - secretRef:
                name: app-secrets

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3002

          livenessProbe:
            httpGet:
              path: /health/live
              port: 3002

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi