import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';
import { trace } from '@opentelemetry/api';

@Injectable()
export class EnterpriseLoggerMiddleware implements NestMiddleware {
  // 1. Define the endpoints you want to ignore
  private readonly ignoredUris = ['/metrics', '/health/live', '/health/ready', '/health/startup']; '];

  use(req: Request, res: Response, next: NextFunction) {

    // 2. Check if the current URI (or originalUrl) is in the ignored list
    if (this.ignoredUris.includes(req.originalUrl || req.url)) {
      return next(); // Skip logging completely and move to the next middleware
    }
    const startTime = Date.now();

    // Listen to when the request finishes to calculate latency and bytes sent
    res.on('finish', () => {
      const durationMs = Date.now() - startTime;

      // Extract the active traceId generated by OpenTelemetry
      // Pull the real hexadecimal trace ID from OpenTelemetry active span context
      const activeSpan = trace.getActiveSpan();
      const realTraceId = activeSpan
        ? activeSpan.spanContext().traceId
        : (req.headers['x-b3-traceid'] || req.headers['traceparent'] || 'no-trace-id');
      //   const activeSpan = trace.getActiveSpan();
      //   const traceId = activeSpan ? activeSpan.spanContext().traceId : req.headers['x-request-id'] || 'no-trace-id';

      const logPayload = {
        timestamp: new Date().toISOString(),
        service_name: process.env.OTEL_SERVICE_NAME || 'nestjs-service',
        trace_id: realTraceId,
        request_id: req.headers['x-request-id'] || null, // Tied back to Nginx $request_id if passed
        client_ip: req.ip || req.headers['x-forwarded-for'] || null,
        method: req.method,
        uri: req.originalUrl,
        status: res.statusCode,
        bytes_sent: parseInt(res.get('Content-Length') || '0', 10),
        latency_ms: durationMs,
        http_referrer: req.get('referrer') || null,
        user_agent: req.get('user-agent') || null,
      };

      // Print it out as a single-line JSON string for Loki/Grafana to parse effortlessly
      console.log(JSON.stringify(logPayload));
    });

    next();
  }
}