
POST http://localhost:3000/auth/register HTTP/1.1
content-type: application/json

{
    "email": "goniusman600@gmail.com",
    "password": "Osman@#1"
}

###

POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "goniusman400@gmail.com",
    "password": "Osman@#1"
}


###

POST http://localhost:3000/books HTTP/1.1
content-type: application/json
authorization: 

{
    "title": "Second Book",
    "author": "Goni",
    "description": "Second. interesting description is here",
    "price": 23,
    "isPublished" : false
}

####

GET http://localhost:80/books HTTP/1.1

###
POST http://localhost:80/orders HTTP/1.1
content-type: application/json

{
    "userId": "2",
    "bookId": "2",
    "price": 23
}

####

GET http://localhost:80/orders HTTP/1.1
