apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.port }}
      protocol: TCP
  selector:
    app: gateway