GET http://localhost:3004/health/live HTTP/1.1

###
GET http://localhost:3004/health/ready HTTP/1.1

###
POST http://localhost:3004/users HTTP/1.1
content-type: application/json

{
    "email": "goniusman400@gmail.com",
    "password": "Osman@#1"
}

###
GET http://localhost:3004/users HTTP/1.1

###
PATCH http://localhost:3004/users/63604bfa-196b-4880-b9e9-47411f1442d7 HTTP/1.1
content-type: application/json

{
    "email": "goniusman400@gmail.com",
    "password": "Osman@#1"
}

###
GET http://localhost:3004/users/8cf899b5-ef55-4551-ac81-a142669c8130 HTTP/1.1

###
DELETE http://localhost:3004/users/485ae64b-eb20-4dee-bc5e-033e556781c9 HTTP/1.1
