global:
  namespace: bookverse

gateway:
  replicaCount: 1
  image:
    repository: docker.io/goniusman/gateway 
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 3000
    type: ClusterIP

auth:
  replicaCount: 1
  image:
    repository: docker.io/goniusman/auth 
    tag: latest
  service:
    port: 3001

book:
  replicaCount: 1
  image:
    repository: docker.io/goniusman/book 
    tag: latest
  service:
    port: 3002

order:
  replicaCount: 1
  image:
    repository: docker.io/goniusman/order 
    tag: latest
  service:
    port: 3003


# auth:
#   image:
#     repository: myrepo/auth
#     tag: latest

# book:
#   image:
#     repository: myrepo/book
#     tag: latest

# order:
#   image:
#     repository: myrepo/order
#     tag: latest

# notification:
#   image:
#     repository: myrepo/notification
#     tag: latest