global:
  namespace: bookverse

gateway:
  replicaCount: 1
  image:
    repository: docker.io/goniusman/gateway 
    tag: "sha-776db50"
    pullPolicy: IfNotPresent
  service:
    port: 3000
    type: ClusterIP

auth:
  replicaCount: 1
  image:
    repository: docker.io/goniusman/auth 
    tag: "sha-c23d2d6"
  service:
    port: 3001

book:
  replicaCount: 1
  image:
    repository: docker.io/goniusman/book 
    tag: "sha-9cff6f7"
  service:
    port: 3002

order:
  replicaCount: 1
  image:
    repository: docker.io/goniusman/order 
    tag: "sha-9d1ae52"
  service:
    port: 3003

notification:
  replicaCount: 1
  image:
    repository: docker.io/goniusman/notification 
    tag: "sha-7b94215"
  # service:
  #   port: 3003


# auth:
#   image:
#     repository: myrepo/auth
#     tag: latest

# book:
#   image:
#     repository: myrepo/book
#     tag: latest

# order:
#   image:
#     repository: myrepo/order
#     tag: latest

# notification:
#   image:
#     repository: myrepo/notification
#     tag: latest