apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: bookverse
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP