apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: bookverse
data:
  PORT: "3000"
  OTEL_SERVICE_NAME: "gateway-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.bookverse.svc.cluster.local:4317"

