global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'mdtajalislam1189@gmail.com'
  smtp_auth_username: 'mdtajalislam1189@gmail.com'
  smtp_auth_password: 'vludjzajibetgtjf'  # Use App Password if Gmail
  smtp_require_tls: true

route:
  receiver: 'email-alert'
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - matchers:
        - severity="critical"
      receiver: 'email-alert'
      repeat_interval: 1h

receivers:
  - name: 'email-alert'
    email_configs:
      # - to: 'osman.g@seenyor.com, majher.i@seenyor.com,'
      - to: 'majher.i@seenyor.com, tajal.islam@seenyor.com'
        send_resolved: true
        headers:
          Subject: '[ALERT] {{ .CommonLabels.alertname }} on {{ .CommonLabels.instance }} ({{ .Status }})'



# EMAIL_FROM=mdtajalislam1189@gmail.com
# EMAIL_PASS=vludjzajibetgtjf
# EMAIL_TITLE=Email verification
# EMAIL_TYPE=gmail
# EMAIL_HOST_NAME=smtp.gmail.com
# EMAIL_SERVER_PORT=465


