apiVersion: v1
kind: Service
metadata:
  name: book
  namespace: bookverse
spec:
  selector:
    app: book
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
  # type: NodePort # <-- Change this from ClusterIP # minikube service auth -n bookverse