apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookverse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/goniusman/microservice-nest'
    targetRevision: main  # Changed from HEAD to your explicit branch name
    path: infra/helm/charts  # FIXED: Points to the exact folder where Chart.yaml lives
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bookverse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
