apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: bookverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: order:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3003

          envFrom:
            - configMapRef:
                name: order-config
            - configMapRef:
                name: app-config
            - secretRef:
                name: order-secrets
            - secretRef:
                name: app-secrets
          # env:
          #   - name: MONGO_URL
          #     value: "mongodb://mongodb:27017/bookverse_orders"
          #   - name: RABBITMQ_URL
          #     value: "amqp://rabbitmq:5672"