apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
  namespace: bookverse
type: Opaque
stringData:
  # Base64 encoding is handled automatically by stringData
  # JWT_SECRET: "test"
  # JWT_ACCESS_SECRET: "my-super-access-secret"
  JWT_REFRESH_SECRETS: "my-super-refresh-secret"