apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.order.replicaCount }}
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: "{{ .Values.order.image.repository }}:{{ .Values.order.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.order.service.port }}

          envFrom:
            - configMapRef:
                name: order-config
            - configMapRef:
                name: app-config
            - secretRef:
                name: order-secrets
            - secretRef:
                name: app-secrets

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3001

          livenessProbe:
            httpGet:
              path: /health/live
              port: 3001

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi