apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: {{ .Values.order.service.port }}
      targetPort: {{ .Values.order.service.port }}
  selector:
    app: order