apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: bookverse
data:
  NODE_ENV: "production"

  AUTH_SERVICE_URL: "http://auth:3001"
  BOOK_SERVICE_URL: "http://book:3002"
  ORDER_SERVICE_URL: "http://order:3003"

  DB_HOST: "postgres" # Matches the PostgreSQL internal Service name
  DB_PORT: "5432"
  DB_NAME: "bookverse_auth"
  
  MONGO_HOST: "mongodb"
  POSTGRES_HOST: "postgres"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"