apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: bookverse
type: Opaque
stringData:
  POSTGRES_USER: bookverse
  POSTGRES_PASSWORD: strong-password
  DB_USERNAME: "bookverse"
  DB_PASSWORD: "bookverse_secure_pass" 

  JWT_SECRET: test
  JWT_REFRESH_SECRET: super-secret-refresh

  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest