apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.auth.replicaCount }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.auth.service.port }}

          envFrom:
            - configMapRef:
                name: auth-config
            - configMapRef:
                name: app-config
            - secretRef:
                name: auth-secrets
            - secretRef:
                name: app-secrets

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3001

          livenessProbe:
            httpGet:
              path: /health/live
              port: 3001

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi